FROM balenalib/%%BALENA_MACHINE_NAME%%-alpine:latest

RUN apk add --no-cache \
    openssh-server \
    openssh-client

COPY start.sh /usr/local/bin/start.sh
RUN chmod +x /usr/local/bin/start.sh

CMD ["/usr/local/bin/start.sh"]
